'use strict';
const assert=require('node:assert/strict');
process.env.SUPABASE_SERVICE_ROLE_KEY='server-test-key';process.env.CRON_SECRET='test-cron';
const store=new Map();let sequence=0,role='admin';const actor=()=>({id:'emp-admin',name:'ผู้ดูแลทดสอบ',role,permissions:{canPrint:true,canEmail:true}});
const settings={business:{name:'กิจการทดสอบ'},email:{enabled:true,provider:'gmail',fromEmail:'sender@example.com',smtpPass:'abcdefghijklmnop',adminEmail:'admin@example.com',reportsEnabled:true,reportTimes:['08:00','18:00'],alerts:{}}};
store.set('settings',{key:'settings',value:settings,updated_at:'1'});store.set('debtors',{key:'debtors',value:[],updated_at:'2'});store.set('cashsales',{key:'cashsales',value:[],updated_at:'3'});
const result=(status,obj)=>new Response(JSON.stringify(obj),{status,headers:{'Content-Type':'application/json'}});
global.fetch=async(url,options={})=>{const u=new URL(url);if(u.pathname.endsWith('/rpc/freshy_read')){if(options.headers.Authorization!=='Bearer valid.token.test')return result(401,{message:'Invalid token'});return result(200,{actor:actor(),data:{settings,debtors:[],cashsales:[]}});}
 if(u.pathname.endsWith('/freshy_store')){const key=u.searchParams.get('key')?.replace(/^eq\./,'');if(options.method==='POST'){const row=JSON.parse(options.body);if(store.has(row.key))return result(409,{message:'Duplicate key'});store.set(row.key,{...row,updated_at:String(++sequence)});return result(201,[store.get(row.key)]);}
 if(options.method==='PATCH'){const old=store.get(key);if(!old||old.updated_at!==u.searchParams.get('updated_at').replace(/^eq\./,''))return result(200,[]);const changed={...old,...JSON.parse(options.body),updated_at:String(++sequence)};store.set(key,changed);return result(200,[changed]);}
 let rows=key&&!key.startsWith('not.in.')?[store.get(key)].filter(Boolean):[...store.values()].sort((a,b)=>a.key.localeCompare(b.key));if(key?.startsWith('not.in.'))rows=rows.filter(x=>!['settings','debtors','cashsales'].includes(x.key));const offset=+(u.searchParams.get('offset')||0),limit=+(u.searchParams.get('limit')||100000);return result(200,rows.slice(offset,offset+limit));}
 throw Error('Unexpected network call: '+u.pathname);
};
let sent=0,transportOptions;require('nodemailer').createTransport=options=>{transportOptions=options;return {sendMail:async message=>{sent++;assert.equal(message.from,'sender@example.com');return {messageId:'test-email-'+sent,accepted:Array.isArray(message.to)?message.to:[message.to],rejected:[]};},close(){}};};
const call=async(handler,method,body,query={},authorization='Bearer valid.token.test')=>{const res={headers:{},statusCode:200,setHeader(k,v){this.headers[k]=v;},status(code){this.statusCode=code;return this;},json(value){this.body=value;return this;}};await handler({method,body,query,headers:{authorization},socket:{remoteAddress:'test'}},res);return res;};
(async()=>{
 const documents=require('./api/document'),backup=require('./api/backup'),email=require('./api/email');
 let r=await call(documents,'GET',null,{id:'bad'},null);assert.equal(r.statusCode,404);r=await call(documents,'POST',{}, {},null);assert.equal(r.statusCode,401);
 const snapshot={schema:1,docNo:'DOC-1',title:'รายงาน',business:{name:'ทดสอบ'},author:{name:'spoof',role:'admin'},tables:[{headers:['ชื่อ','ยอด'],rows:[['<img src=x onerror=alert(1)>','100']]}],summaries:['รวม 100 บาท'],metadata:'ข้อมูลเอกสาร'};
 r=await call(documents,'POST',{snapshot});assert.equal(r.statusCode,200);assert.match(r.body.id,/^[a-f0-9]{64}$/);const id=r.body.id;r=await call(documents,'GET',null,{id},null);assert.equal(r.body.document.docNo,'DOC-1');assert.equal(r.body.document.author.name,actor().name);assert.equal(r.body.document.tables[0].rows[0][0],snapshot.tables[0].rows[0][0]);assert(!('settings' in r.body.document));assert.equal((await call(documents,'GET',null,{id:'f'.repeat(64)},null)).statusCode,404);
 role='staff';assert.equal((await call(backup,'GET')).statusCode,403);role='admin';for(let i=0;i<1005;i++)store.set('document:fixture'+i,{key:'document:fixture'+i,value:{schema:1},updated_at:'old'});let cursor=0,all=[];do{r=await call(backup,'GET',null,{cursor});all.push(...r.body.rows);cursor=r.body.nextCursor;}while(cursor!==null);assert.equal(all.length,1006);assert(all.some(x=>x.key==='document:'+id));
 assert.equal((await call(email,'POST',{type:'login',to:'admin@example.com',subject:'Test',html:'<p>test</p>'}, {},null)).statusCode,401);
 r=await call(email,'POST',{type:'login',to:'admin@example.com',subject:'Test',html:'<p>test</p>'});assert(r.body.ok);assert.equal(transportOptions.host,'smtp.gmail.com');assert.equal(transportOptions.port,465);assert.equal(transportOptions.secure,true);
 settings.email.alerts.login=false;assert.equal((await call(email,'POST',{type:'login',to:'admin@example.com',subject:'Test',html:'x'})).statusCode,403);settings.email.alerts.login=true;role='staff';assert.equal((await call(email,'POST',{type:'login',to:'stranger@example.com',subject:'Test',html:'x'})).statusCode,403);role='admin';
 const F=require('./features'),original=F.bangkokParts;F.bangkokParts=()=>({date:'2026-10-04',time:'08:30'});const reports=require('./api/daily-report');r=await call(reports,'POST',{});assert(r.body.ok);const count=sent;r=await call(reports,'POST',{});assert.equal(r.body.sentCount,0);assert.equal(sent,count,'A second invocation must not resend the same report');F.bangkokParts=original;assert.equal(reports.summarize({debtors:[{status:'paid',paidAt:'2026-10-03T18:00:00Z',total:100}],cashsales:[]},'2026-10-04').paidTotal,100);
 const pdf=await reports.pdfReport({name:'กิจการทดสอบ'},'08:00','2026-10-04',reports.summarize({debtors:[],cashsales:[]},'2026-10-04'));assert(pdf.subarray(0,4).toString()==='%PDF');assert(pdf.length>5000);
 console.log('Passed: immutable scoped documents, opaque QR tokens, no-login document read, admin-only backup pagination, Gmail TLS, recipient permissions, notification toggles, persistent report deduplication, Thai timezone, and PDF generation. No real database or email was used.');
})().catch(e=>{console.error(e);process.exitCode=1;});
