(function(root){
'use strict';
const headers=['type','id','customerId','code','name','area','moo','village','address','phone','debtDate','jugs','packs','jugAmount','packAmount','total','note'];
const resetCategories={unpaid:'ลูกหนี้ค้างชำระ',paid:'ประวัติรับชำระ',customers:'ลูกค้า (รวมลูกหนี้และคำขอที่เกี่ยวข้อง)',cashsales:'รายการขายเงินสด',employees:'พนักงาน (เก็บแอดมินที่ใช้งานอยู่)',products:'สินค้า',villages:'หมู่บ้าน',audit:'ประวัติการแก้ไขเดิม',approvals:'คำขออนุมัติ',documents:'เอกสารและ QR เดิม',emailLogs:'ประวัติอีเมล',settings:'การตั้งค่าระบบ'};
function parse(text){
 if(typeof text!=='string'||text.length>2000000)throw Error('ไฟล์ CSV ต้องไม่เกิน 2 MB');
 text=text.replace(/^\uFEFF/,'');let rows=[],row=[],cell='',quoted=false,closed=false;
 for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'){if(text[i+1]==='"'){cell+='"';i++;}else{quoted=false;closed=true;}}else cell+=c;}
 else if(c==='"'){if(cell||closed)throw Error('รูปแบบเครื่องหมายคำพูดใน CSV ไม่ถูกต้อง');quoted=true;}
 else if(c===','||c==='\n'||c==='\r'){row.push(cell);cell='';closed=false;if(c!==','){if(c==='\r'&&text[i+1]==='\n')i++;if(row.some(v=>v.trim()))rows.push(row);row=[];}}
 else{if(closed)throw Error('มีข้อความหลังเครื่องหมายคำพูดใน CSV');cell+=c;}}
 if(quoted)throw Error('CSV มีเครื่องหมายคำพูดที่ยังไม่ปิด');row.push(cell);if(row.some(v=>v.trim()))rows.push(row);
 if(!rows.length)throw Error('ไฟล์ CSV ไม่มีข้อมูล');if(rows.length>2001)throw Error('นำเข้าได้ไม่เกิน 2,000 แถวต่อครั้ง');
 const keys=rows.shift().map(v=>v.trim());if(new Set(keys).size!==keys.length||keys.some(v=>!v))throw Error('หัวคอลัมน์ว่างหรือซ้ำ');
 return rows.map((r,i)=>{if(r.length!==keys.length)throw Error('แถว '+(i+2)+' จำนวนคอลัมน์ไม่ตรงกับหัวตาราง');return Object.fromEntries(keys.map((k,j)=>[k,r[j].replace(/^'(?=[=+@\-\t\r])/,'').trim()]));});
}
function cells(db,kind='all'){
 const result=[];if(kind!=='debtors')for(const c of db.customers||[])result.push({type:'customers',id:c.id,code:c.code,name:c.name,area:c.area,moo:c.moo,village:c.village,address:c.address,phone:c.phone});
 if(kind!=='customers')for(const d of db.debtors||[])if(d.status==='unpaid'){const c=(db.customers||[]).find(c=>c.id===d.customerId)||{};result.push({...c,...d,type:'debtors',name:d.customerName,code:c.code});}
 return result.map(r=>headers.map(h=>r[h]??''));
}
function date(v){if(!v)throw Error('กรุณาระบุ debtDate');let y,m,d;let match=v.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);if(match)[,y,m,d]=match;else{match=v.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(!match)throw Error('วันที่ต้องเป็น YYYY-MM-DD หรือ DD/MM/YYYY');[,d,m,y]=match;}y=+y;if(y>=2400)y-=543;m=+m;d=+d;const dt=new Date(Date.UTC(y,m-1,d));if(y<1900||y>2200||dt.getUTCFullYear()!==y||dt.getUTCMonth()!==m-1||dt.getUTCDate()!==d)throw Error('วันที่ไม่ถูกต้อง');return `${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`;}
function plan(text,db,actor,makeId,now=new Date().toISOString()){
 if(actor?.role!=='admin')throw Error('เฉพาะแอดมินเท่านั้น');const input=parse(text),customers=structuredClone(db.customers||[]),debts=structuredClone(db.debtors||[]),changes=[],seen=new Set(),counts={customers:0,debtors:0,updated:0,skipped:0};
 function put(k,v,old){const key=k+':'+v.id;if(seen.has(key))throw Error('รหัสรายการซ้ำในไฟล์: '+v.id);seen.add(key);if(old&&JSON.stringify(old)===JSON.stringify(v)){counts.skipped++;return;}changes.push({collection:k,id:v.id,expected:old||null,value:v});counts[old?'updated':k]++;}
 function area(r){if(!['nai','other'].includes(r.area))throw Error('area ต้องเป็น nai หรือ other');return r.area;}
 function findCustomer(r,byId){if(byId){const c=customers.find(c=>c.id===byId);if(!c)throw Error('ไม่พบ customerId: '+byId);return c;}const matches=customers.filter(c=>r.code?c.code===r.code:c.name===r.name&&c.area===r.area&&String(c.moo||'')===String(r.moo||'')&&String(c.village||'')===String(r.village||''));if(matches.length>1)throw Error('ชื่อลูกค้าซ้ำ กรุณาระบุ customerId');return matches[0];}
 // Customers are processed first so the file may list debts before customers.
 for(const [i,r] of input.entries())try{if(!['customers','debtors'].includes(r.type))throw Error('type ต้องเป็น customers หรือ debtors (ไม่รับประวัติชำระแล้ว)');if(r.type!=='customers')continue;area(r);if(!r.name)throw Error('กรุณาระบุ name');const old=r.id?customers.find(c=>c.id===r.id):findCustomer(r);const duplicate=r.code&&customers.find(c=>c.code===r.code&&c.id!==(old?.id||r.id));if(duplicate)throw Error('รหัสลูกค้าซ้ำ: '+r.code);const c={...old,id:old?.id||r.id||makeId(),code:r.code||old?.code||'CSV-'+makeId().slice(-8),name:r.name,area:r.area,moo:r.moo||'',village:r.village||'',address:r.address||'',phone:r.phone||'',createdBy:old?.createdBy||actor.id,createdAt:old?.createdAt||now,managedBy:old?.managedBy||actor.id,responsibleBy:old?.responsibleBy||actor.id};put('customers',c,old);const n=customers.findIndex(x=>x.id===c.id);if(n<0)customers.push(c);else customers[n]=c;}catch(e){throw Error('แถว '+(i+2)+': '+e.message);}
 for(const [i,r] of input.entries())try{if(r.type!=='debtors')continue;if(r.status&&r.status!=='unpaid')throw Error('นำเข้าได้เฉพาะลูกหนี้ค้างชำระ');area(r);const c=findCustomer(r,r.customerId);if(!c)throw Error('ไม่พบลูกค้า กรุณาเพิ่มแถว customers หรือระบุ customerId');if(c.area!==r.area)throw Error('พื้นที่ลูกค้าและลูกหนี้ไม่ตรงกัน');const num=k=>{const v=r[k]||'0';if(!/^\d+(?:\.\d{1,2})?$/.test(v.replace(/,/g,'')))throw Error(k+' ต้องเป็นจำนวนที่ไม่ติดลบ');const n=Number(v.replace(/,/g,''));if(!Number.isFinite(n)||n>1000000000||(['jugs','packs'].includes(k)&&!Number.isInteger(n)))throw Error(k+' ไม่ถูกต้อง');return n;};const amounts=Object.fromEntries(['jugs','packs','jugAmount','packAmount'].map(k=>[k,num(k)]));const total=Math.round((amounts.jugAmount+amounts.packAmount)*100)/100;if(r.total&&Number(r.total.replace(/,/g,''))!==total)throw Error('total ต้องเท่ากับ jugAmount + packAmount');const debtDate=date(r.debtDate),old=r.id?debts.find(d=>d.id===r.id):null;if(old?.status==='paid')throw Error('ห้ามนำเข้าทับประวัติรับชำระ');if(old&&old.customerId!==c.id)throw Error('ห้ามเปลี่ยนลูกค้าของรายการเดิม');const v={...old,id:old?.id||r.id||makeId(),customerId:c.id,customerName:c.name,area:c.area,moo:c.moo||'',village:c.village||'',debtDate,...amounts,total,status:'unpaid',note:r.note||'',createdBy:old?.createdBy||actor.id,createdAt:old?.createdAt||now,responsibleBy:old?.responsibleBy||c.responsibleBy||actor.id};if(!r.id&&debts.some(d=>d.status==='unpaid'&&d.customerId===v.customerId&&d.debtDate===v.debtDate&&['jugs','packs','jugAmount','packAmount','note'].every(k=>(d[k]||'')===(v[k]||'')))){counts.skipped++;continue;}put('debtors',v,old);const n=debts.findIndex(d=>d.id===v.id);if(n<0)debts.push(v);else debts[n]=v;}catch(e){throw Error('แถว '+(i+2)+': '+e.message);}
 if(!input.length)throw Error('ไฟล์ CSV ไม่มีแถวข้อมูล');return {changes,counts,rows:input.length};
}
const api={headers,resetCategories,parse,cells,plan,date};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.FreshyData=api;
})(typeof window!=='undefined'?window:globalThis);
