(async function(){'use strict';
 const root=document.getElementById('document');
 const add=(tag,value,parent=root,cls='')=>{const e=document.createElement(tag);if(value!==null)e.textContent=String(value??'');if(cls)e.className=cls;parent.append(e);return e;};
 try{
  const params=new URLSearchParams(location.search),id=params.get('id');if(!/^[a-f0-9]{64}$/.test(id||''))throw Error('ไม่พบเอกสาร');
  const privateAccess=params.get('access')==='private',headers={};
  if(privateAccess){const config=window.FRESHY_CONFIG||{},client=supabase.createClient(config.supabaseUrl,config.supabaseKey),session=(await client.auth.getSession()).data.session;if(!session){location.replace('/?document='+id);return;}headers.Authorization='Bearer '+session.access_token;}
  const r=await fetch('/api/document?id='+encodeURIComponent(id)+(privateAccess?'&access=private':''),{headers,cache:'no-store',referrerPolicy:'no-referrer',signal:AbortSignal.timeout(25000)}),data=await r.json();
  if(r.status===401&&privateAccess){location.replace('/?document='+id);return;}if(!r.ok||!data.ok)throw Error(data.error||'โหลดเอกสารไม่สำเร็จ');const d=data.document;
  root.replaceChildren();root.className='document-screen doc-page';
  const toolbar=document.createElement('div');toolbar.className='document-toolbar';root.before(toolbar);add('p','เอกสารเลขที่ '+d.docNo,toolbar);const button=add('button','พิมพ์ / บันทึก PDF',toolbar);button.type='button';button.id='printSavedDocument';button.onclick=async()=>{if(document.fonts)await document.fonts.ready;await Promise.all([...root.querySelectorAll('img')].map(img=>img.complete?Promise.resolve():new Promise(resolve=>{img.onload=resolve;img.onerror=resolve;setTimeout(resolve,5000);})));window.print();};
  const head=add('header',null,root,'doc-head');add('div','',head,'doc-logo');const title=add('div',null,head,'doc-title');add('div',d.business.name,title,'factory');add('div',[d.business.address,d.business.phone?'โทรศัพท์ '+d.business.phone:'',d.business.taxId?'เลข อย. '+d.business.taxId:''].filter(Boolean).join(' · '),title,'factory-sub');add('h1',d.title,title,'report-name');
  const control=add('div',null,head,'doc-control');const qr=qrcode(0,'M');qr.addData(location.origin+'/document?id='+id+(privateAccess?'&access=private':''));qr.make();const img=add('img',null,control,'document-qr');img.src='data:image/svg+xml;base64,'+btoa(qr.createSvgTag({cellSize:3,margin:12,scalable:true}));img.alt='QR เอกสาร '+d.docNo;add('span','เลขที่เอกสาร',control);add('strong',d.docNo,control);
  const meta=add('div',null,root,'doc-meta');add('span','วันที่ออกเอกสาร '+new Date(d.issuedAt).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'})+' น.',meta);add('span','ผู้จัดทำ '+d.author.name,meta);
  for(const t of d.tables){const section=add('section',null,root,'doc-customer-block'),table=add('table',null,section,'doc-table');if(t.title)add('caption',t.title,table);if(t.widths?.length===t.headers.length){const group=add('colgroup',null,table);for(const w of t.widths){const col=add('col',null,group);col.style.width=w+'%';}}const head=add('thead',null,table),tr=add('tr',null,head);for(const h of t.headers)add('th',h,tr);const body=add('tbody',null,table);for(const row of t.rows){const tr=add('tr',null,body);if(/^รวม/.test(row[0]||''))tr.className='doc-customer-total';for(let i=0;i<row.length;i++){const td=add('td',row[i],tr,t.alignments?.[i]==='right'?'r':t.alignments?.[i]==='left'?'l':'');if(i===0&&/^รวม/.test(row[0]||'')){let span=1;while(i+1<row.length&&row[i+1]===''){span++;i++;}td.colSpan=span;td.className='l';}}}}
  for(const summary of d.summaries)add('p',summary,root,'doc-summary');
  const signatures=d.signatures?.length?d.signatures:[{name:d.author.name,role:'ผู้จัดทำข้อมูล'},{name:'',role:'พนักงานส่งน้ำ'},{name:'',role:'ผู้ตรวจสอบ'},{name:'',role:'ผู้อนุมัติ'}],signs=add('div',null,root,'sign-row');for(const s of signatures){const box=add('div',null,signs,'sign-box');add('div','('+(s.name||'........................................')+')',box,'line');add('div',s.role,box,'role');add('div','วันที่ .... / .... / ........',box,'sign-date');}
  add('footer','เลขที่เอกสาร '+d.docNo+' ออกโดยระบบสารสนเทศจัดการลูกหนี้ · '+d.business.name,root,'doc-foot');document.title=d.docNo+' '+d.title;
 }catch(e){root.replaceChildren();root.id='documentError';add('h1','ไม่สามารถแสดงเอกสาร');add('p',e.message);}
})();
