'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
const snapshot={schema:1,docNo:'FWD-REFERENCE',title:'รายงานลูกหนี้ค้างชำระ',business:{name:'กิจการทดสอบ',address:'ที่อยู่ทดสอบ'},author:{name:'ผู้จัดทำทดสอบ'},issuedAt:'2026-10-04T10:00:00Z',tables:[{title:'ลูกหนี้: ลูกค้าทดสอบ',headers:['ลำดับ','วันที่ค้าง','ยอดรวม'],widths:[10,55,35],alignments:['center','center','right'],rows:[['1','01/10/2569','20'],['รวม ลูกค้าทดสอบ','','20']]}],summaries:['ยอดค้าง 20 บาท'],signatures:[{name:'ผู้จัดทำทดสอบ',role:'ผู้จัดทำข้อมูล'},{name:'',role:'ผู้ตรวจสอบ'}]};
const pause=()=>new Promise(resolve=>setTimeout(resolve,20));
async function view(status=200){
 const dom=new JSDOM(fs.readFileSync('document.html','utf8'),{url:'https://freshy.test/document?id='+'a'.repeat(64)+'&access=private',runScripts:'outside-only'}),w=dom.window;let requests=0,prints=0;
 w.FRESHY_CONFIG={supabaseUrl:'https://db.test',supabaseKey:'public-key'};w.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:{access_token:'private-token'}}})}})};
 w.fetch=async(url,options)=>{requests++;assert(url.includes('&access=private'));assert.equal(options.headers.Authorization,'Bearer private-token');return {status,ok:status===200,json:async()=>status===200?{ok:true,document:snapshot}:{ok:false,error:'ไม่มีสิทธิ์อ่านเอกสาร'}};};
 w.print=()=>prints++;w.eval(fs.readFileSync('vendor/qrcode.js','utf8'));w.eval(fs.readFileSync('document-view.js','utf8'));await pause();return {dom,w,get requests(){return requests;},get prints(){return prints;}};
}
(async()=>{const v=await view(),d=v.w.document;assert.equal(d.querySelectorAll('a,nav,#appShell').length,0,'QR document has no navigation or return-to-system link');assert.equal(d.querySelector('.doc-control strong').textContent,snapshot.docNo);assert.equal(d.querySelector('.doc-table caption').textContent,snapshot.tables[0].title);assert.equal(d.querySelector('.doc-customer-total td').colSpan,2);assert.equal(d.querySelectorAll('.sign-box').length,2);assert(d.querySelector('img.document-qr'));d.querySelector('#printSavedDocument').click();d.querySelector('img').dispatchEvent(new v.w.Event('load'));await pause();assert.equal(v.prints,1);assert.equal(v.requests,1,'Reprinting must use the same saved snapshot and document number');assert.equal(d.querySelector('.doc-control strong').textContent,snapshot.docNo);v.dom.window.close();const denied=await view(403);assert(!denied.w.document.querySelector('#printSavedDocument'));assert(denied.w.document.body.textContent.includes('ไม่มีสิทธิ์'));denied.dom.window.close();console.log('Passed: authenticated saved document rendering, QR, merged totals, signatures, permission errors and printing without reissuing the document.');})().catch(e=>{console.error(e);process.exitCode=1;});
