'use strict';const assert=require('node:assert/strict');
(async()=>{
 const {handler}=await import('./supabase/functions/freshy-access/index.mjs');
 let role='admin',employees=[],authUsers=[],creates=0,tokenCalls=0,villages=null,revision='r1';
 const env=k=>({SUPABASE_URL:'https://fixture.supabase.co',SUPABASE_ANON_KEY:'anon-fixture',SUPABASE_SERVICE_ROLE_KEY:'edge-injected-secret'})[k];
 const response=(v,status=200)=>new Response(JSON.stringify(v),{status});
 const net=async(url,o)=>{const u=new URL(url),b=o.body?JSON.parse(o.body):{};
  if(u.pathname.endsWith('/rpc/freshy_read')){if(!['Bearer admin-token','Bearer staff-token'].includes(o.headers.Authorization))return response({message:'MEMBER_NOT_FOUND'},403);return response({actor:{id:role==='admin'?'admin':'staff',name:'Fixture',role,permissions:{pages:{debtorsOther:true}}},data:{settings:{_resetRevision:revision},employees:structuredClone(employees)}});}
  if(u.pathname.endsWith('/admin/users')&&o.method==='POST'){assert.equal(o.headers.apikey,'edge-injected-secret');creates++;if(authUsers.some(x=>x.email===b.email))return response({msg:'already registered'},422);const user={...b,id:'auth-'+creates};authUsers.push(user);return response(user);}
  if(u.pathname.endsWith('/admin/users')&&o.method==='GET')return response({users:authUsers});
  if(u.pathname.includes('/admin/users/')&&o.method==='PUT'){const user=authUsers.find(x=>url.endsWith(x.id));Object.assign(user,b);return response(user);}
  if(u.pathname.endsWith('/rpc/freshy_apply')){assert.equal(o.headers.Authorization,'Bearer admin-token');assert.equal(o.headers['x-freshy-revision'],revision);const c=b.changes[0];assert.equal(c.collection,'employees');assert(!('password' in c.value));assert(authUsers.some(x=>x.email===c.value.email&&x.email_confirm));employees=employees.filter(e=>e.id!==c.id).concat(c.value);return response({actor:{id:'admin',role:'admin'},data:{settings:{_resetRevision:revision},employees:structuredClone(employees)}});}
  if(u.pathname.endsWith('/token')){tokenCalls++;const user=authUsers.find(x=>x.email===b.email&&x.password===b.password);return user?response({access_token:'staff-token',refresh_token:'refresh-fixture',user}):response({message:'bad password'},400);}
  if(u.pathname.endsWith('/freshy_store')){assert.equal(o.headers.apikey,'edge-injected-secret');const key=u.searchParams.get('key');if(key==='eq.employees')return response([{value:employees}]);if(key==='eq.settings')return response([{value:{_resetRevision:revision}}]);if(o.method==='POST'){assert.equal(b.key,'villages');villages={...b,updated_at:'v1'};return response([villages],201);}if(o.method==='PATCH'){villages={...villages,...b};return response([villages]);}return response(villages?[villages]:[]);}
  throw Error('Unexpected path '+u.pathname);
 };
 const call=async(body,token='admin-token')=>{const r=await handler(new Request('https://fixture/access',{method:'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json','x-forwarded-for':'fixture-ip'},body:JSON.stringify(body)}),env,net);return {status:r.status,body:await r.json()};};
 const employee={id:'employee-1',name:'พนักงานทดสอบ',code:'1007',role:'staff',status:'active',contactEmail:'',permissions:{pages:{debtorsOther:true},canPrint:false,canEmail:false}};
 const body={action:'employee',employee,password:'fixture-password',expectedEmployee:null,expectedRevision:'r1'};
 assert.equal((await call(body,'invalid')).status,403);role='staff';assert.equal((await call(body,'staff-token')).status,403);role='admin';assert.equal((await call({...body,password:'123'})).status,400);assert.equal((await call({...body,expectedRevision:'old'})).status,409);assert.equal(creates,0);
 let r=await call(body);assert.equal(r.status,200);assert.equal(employees[0].status,'active');assert(employees[0].email.endsWith('@employees.freshywater.in.th'));assert(!JSON.stringify(r.body).includes('fixture-password'));assert(!JSON.stringify(r.body).includes('edge-injected-secret'));assert.equal(creates,1);
 r=await call(body);assert.equal(r.status,200,'Retry after lost response is idempotent');assert.equal(creates,1);assert.equal(employees.length,1);
 r=await call({...body,employee:{...employee,id:'another'}});assert.equal(r.status,409);assert.equal(creates,1);
 role='staff';r=await call({action:'login',code:'1007',password:'wrong'},'anon-fixture');assert.equal(r.status,401);r=await call({action:'login',code:'1007',password:'fixture-password'},'anon-fixture');assert.equal(r.status,200);assert.equal(r.body.access_token,'staff-token');employees[0].status='inactive';const before=tokenCalls;assert.equal((await call({action:'login',code:'1007',password:'fixture-password'},'anon-fixture')).status,401);assert.equal(tokenCalls,before,'Disabled membership cannot even request a token');
 r=await call({action:'village',name:'บ้านทดสอบ'},'staff-token');assert.equal(r.status,200);assert.equal(r.body.village.code,'V001');assert.equal(villages.value.length,1);r=await call({action:'village',name:'บ้านทดสอบ'},'staff-token');assert.equal(villages.value.length,1);
 // A pending registry record receives its own managed identity, not control of another person's email.
 role='admin';const pending={...employee,id:'pending-2',code:'1008',status:'pending',email:'unrelated@example.com'};employees.push(pending);r=await call({...body,employee:{...employee,id:'pending-2',code:'1008'},expectedEmployee:pending});assert.equal(r.status,200);assert.equal(employees.find(e=>e.id==='pending-2').status,'active');assert(!authUsers.some(u=>u.email==='unrelated@example.com'));
 // The Vercel proxy needs no copied privileged key and rejects staff before forwarding.
 delete process.env.SUPABASE_SERVICE_ROLE_KEY;const C=require('./api/_lib/core');const original=C.authenticate,originalJson=C.json;let forwarded=0;C.authenticate=async(req,admin)=>{assert(admin);if(req.headers.authorization==='Bearer staff')throw new C.HttpError(403,'admin only');};C.json=async(path,o)=>{assert.equal(path,'/functions/v1/freshy-access');assert.equal(o.headers.Authorization,'Bearer '+C.anon);assert.equal(o.headers['x-freshy-authorization'],'Bearer admin');forwarded++;return {ok:true,payload:{}};};
 const proxy=require('./api/employees');const res={statusCode:200,setHeader(){},status(v){this.statusCode=v;return this;},json(v){this.body=v;return this;}};await proxy({method:'POST',headers:{authorization:'Bearer staff'},body},res);assert.equal(res.statusCode,403);assert.equal(forwarded,0);res.statusCode=200;await proxy({method:'POST',headers:{authorization:'Bearer admin'},body},res);assert.equal(res.statusCode,200);assert.equal(forwarded,1);C.authenticate=original;C.json=originalJson;
 console.log('Passed: one-step employee creation, confirmed managed identity, no email confirmation, admin-only setup, no password persistence, idempotent retry, code login, disabled access, pending activation, staff village saves after reset, and no Vercel service key setup. No real account or database was modified.');
})().catch(e=>{console.error(e);process.exitCode=1;});
