(function(root){'use strict';
function bangkokParts(now=new Date()){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(now).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return {date:p.year+'-'+p.month+'-'+p.day,time:p.hour+':'+p.minute,year:+p.year,month:+p.month,day:+p.day};}
function latestBackupDate(now=new Date()){const p=bangkokParts(now),c=[];for(let back=0;back<2;back++){const d=new Date(Date.UTC(p.year,p.month-1-back,1)),y=d.getUTCFullYear(),m=d.getUTCMonth()+1,last=new Date(Date.UTC(y,m,0)).getUTCDate();for(const day of [1,15,31]){if(day>last)continue;const s=y+'-'+String(m).padStart(2,'0')+'-'+String(day).padStart(2,'0');if(s<=p.date)c.push(s);}}return c.sort().pop();}
function csvCell(v){let s=String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
function csv(headers,rows){return '\uFEFF'+[headers,...rows].map(r=>r.map(csvCell).join(',')).join('\r\n');}
function villageCode(villages,name){const used=new Set(villages.map(x=>x.code).filter(Boolean));const codes=new Map();let next=1;for(const v of villages){if(v.code){codes.set(v.id,v.code);continue;}while(used.has('V'+String(next).padStart(3,'0')))next++;const code='V'+String(next++).padStart(3,'0');used.add(code);codes.set(v.id,code);}const found=villages.find(x=>String(x.name).trim()===String(name).trim());if(found)return codes.get(found.id);let max=0;for(const code of used){const m=String(code).match(/^V(\d+)$/);if(m)max=Math.max(max,+m[1]);}return 'V'+String(max+1).padStart(3,'0');}
function scheduleTimes(value){const list=(Array.isArray(value)?value:String(value||'').split(',')).map(x=>String(x).trim());if(!list.length||list.length>4||list.some(x=>!/^([01]\d|2[0-3]):[0-5]\d$/.test(x)))throw Error('กำหนดเวลาในรูปแบบ HH:mm ได้ 1–4 รอบ');return [...new Set(list)].sort();}
function documentSnapshot(html,docNo,business,author,doc){const el=doc.createElement('div');el.innerHTML=html;const tables=[...el.querySelectorAll('.doc-table')].map(t=>({headers:[...t.querySelectorAll('thead th')].map(x=>x.textContent.trim()),rows:[...t.querySelectorAll('tbody tr')].map(r=>[...r.querySelectorAll('td')].map(x=>x.textContent.trim()))}));return {schema:1,docNo,title:el.querySelector('.report-name')?.textContent.trim()||'รายงานข้อมูล',issuedAt:new Date().toISOString(),business:{name:business.name,address:business.address,phone:business.phone,taxId:business.taxId},author:{name:author.name,role:author.role},tables,metadata:el.querySelector('.doc-meta')?.textContent.trim()||'',summaries:[...el.querySelectorAll('.doc-summary')].map(x=>x.textContent.trim())};}
const api={bangkokParts,latestBackupDate,csv,villageCode,scheduleTimes,documentSnapshot};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.FreshyFeatures=api;
})(typeof window!=='undefined'?window:globalThis);
