'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');const F=require('./features');
const now=d=>new Date(d+'T05:00:00Z');
assert.equal(F.latestBackupDate(now('2026-04-30')),'2026-04-15');assert.equal(F.latestBackupDate(now('2026-03-31')),'2026-03-31');assert.equal(F.latestBackupDate(new Date('2026-09-30T18:00:00Z')),'2026-10-01');assert.equal(F.latestBackupDate(now('2028-02-29')),'2028-02-15');assert.deepEqual(F.scheduleTimes('18:00,08:00,08:00'),['08:00','18:00']);assert.throws(()=>F.scheduleTimes('24:00'));
const csv=F.csv(['ชื่อ','ยอด'],[['=HYPERLINK("bad")',100],['สมชาย,ทดสอบ','a"b\nnext']]);assert(csv.startsWith('\uFEFF'));assert(csv.includes('"\'=HYPERLINK(""bad"")"'));assert(csv.includes('"สมชาย,ทดสอบ"'));assert(csv.includes('"a""b\nnext"'));
assert.equal(F.villageCode([{id:'a',name:'เดิม',code:'V012'}],'ใหม่'),'V013');assert.equal(F.villageCode([{id:'a',name:'เดิม',code:'CUSTOM'}],'เดิม'),'CUSTOM');assert.equal(F.villageCode([{id:'a',name:'เดิม',code:'V002'},{id:'b',name:'ไม่มีรหัส'}],'ไม่มีรหัส'),'V001');
function dom(initial){const d=new JSDOM(fs.readFileSync('index.html','utf8'),{url:'https://freshy.test/design-preview',runScripts:'outside-only'}),w=d.window;w.FRESHY_PREVIEW=true;w.FRESHY_CONFIG={mode:'demo'};if(initial)w.localStorage.setItem('freshywater_demo_v8',JSON.stringify(initial));w.print=()=>{};w.setInterval=()=>0;w.scrollTo=()=>{};w.confirm=()=>true;w.URL.createObjectURL=()=> 'blob:unit-test';w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=()=>{};w.matchMedia=()=>({matches:false,addEventListener(){}});for(const file of ['sync.js','features.js','vendor/qrcode.js','app.js'])w.eval(fs.readFileSync(file,'utf8'));return d;}
const pause=()=>new Promise(r=>setTimeout(r,15));
(async()=>{
 const d=dom(),w=d.window,$=s=>w.document.querySelector(s);$('#loginCode').value='7716';$('#loginBtn').click();assert(!$('#appShell').classList.contains('hidden'));
 const nav=page=>{$(`[data-page="${page}"]`).click();};
 nav('debtorsOther');$('#addDebtorBtn').click();$('#f_name').value='ลูกค้าทดสอบใหม่';$('#f_name').dispatchEvent(new w.Event('input'));$('#f_area').value='บ้านใหม่';$('#f_area').dispatchEvent(new w.Event('input'));assert.equal($('#f_villageCode').value,'V004');$('#f_jugs').value='2';$('#f_ja').value='40';$('#saveDebtor').click();await pause();assert($('#continueDebtorEntry'));let saved=JSON.parse(w.localStorage.getItem('freshywater_demo_v8'));assert(saved.debtors.some(x=>x.customerName==='ลูกค้าทดสอบใหม่'&&x.total===40));assert(saved.villages.some(x=>x.name==='บ้านใหม่'&&x.code==='V004'));
 $('#modalBox').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert($('#f_name'));$('#f_name').value='abc';$('#f_name').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Backspace',bubbles:true}));assert($('#f_name'),'Backspace in a text field must not cancel the debt form');w.closeModal();$('#addDebtorBtn').click();$('#f_name').value='อีกคน';$('#f_name').dispatchEvent(new w.Event('input'));$('#f_area').value='บ้านใหม่';$('#f_jugs').value='1';$('#f_ja').value='20';$('#saveDebtor').click();await pause();$('#modalBox').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Backspace',bubbles:true}));assert($('#modalBackdrop').classList.contains('hidden'));
 nav('employees');$('.editEmp').click();assert.equal(w.document.querySelectorAll('#e_email').length,1);assert($('#e_canEmail'));w.closeModal();
 nav('customersOther');assert($('#exportCsv'));$('#custPrintBtn').click();assert($('#printDocumentQr').checked);$('#printDocumentQr').checked=false;$('#confirmDocumentPrint').click();await pause();assert($('#printArea .doc-control'));assert(!$('#printArea').textContent.includes('หน่วยงาน'));assert(!$('#printArea').querySelector('img.document-qr'));
 const firstNumber=$('#printArea .doc-control strong').textContent.replace('เลขที่ ','');assert(/^CUS-[A-Z0-9]{13}$/.test(firstNumber));$('#custPrintBtn').click();$('#printDocumentQr').checked=false;$('#confirmDocumentPrint').click();await pause();assert.notEqual($('#printArea .doc-control strong').textContent.replace('เลขที่ ',''),firstNumber);
 const spanExample=F.documentSnapshot('<div class="report-name">ทดสอบ</div><table class="doc-table"><thead><tr><th>ชื่อ</th><th>ถัง</th><th>ยอด</th></tr></thead><tbody><tr><td colspan="2">รวม</td><td>40</td></tr></tbody></table>','TEST',{}, {},w.document);assert.deepEqual(spanExample.tables[0].rows[0],['รวม','','40']);
 nav('debtorsOther');$('#emailReportBtn').click();assert.equal($('#er_fmt').value,'formal');assert($('#er_fmt').textContent.includes('PDF'));w.closeModal();
 const previous=w.document.documentElement.dataset.theme;$('#themeToggle').click();assert.notEqual(w.document.documentElement.dataset.theme,previous);$('#themeToggle').click();assert.equal(w.document.documentElement.dataset.theme,previous);
 nav('settings');$('[data-t="profile"]').click();assert($('#profileFile'));$('[data-t="email"]').click();assert($('#em_times'));assert([...$('#em_prov').options].some(x=>x.value==='gmail'));$('[data-t="system"]').click();const before=JSON.parse(w.localStorage.getItem('freshywater_demo_v8'));$('#resetBtn').click();await pause();const after=JSON.parse(w.localStorage.getItem('freshywater_demo_v8'));assert.deepEqual(after.settings,before.settings);assert.deepEqual(after.employees,before.employees);assert(!after.debtors.some(x=>x.customerName==='ลูกค้าทดสอบใหม่'));assert(!after.debtors.some(x=>x.isDemo===true));
 // A new view renders 30 customer groups from 1,000 debtors. CSV still exports all.
 const bulk=JSON.parse(w.localStorage.getItem('freshywater_demo_v8'));bulk.customers=[];bulk.debtors=[];for(let i=0;i<1000;i++){bulk.customers.push({id:'c'+i,code:'C'+i,name:'ราย '+i,area:'other',village:'บ้านใหม่',createdBy:'emp_admin'});bulk.debtors.push({id:'d'+i,customerId:'c'+i,customerName:'ราย '+i,area:'other',village:'บ้านใหม่',status:'unpaid',jugs:1,packs:0,jugAmount:20,packAmount:0,total:20,debtDate:'2026-10-01',createdAt:new Date().toISOString(),createdBy:'emp_admin'});}bulk.debtors.push({...bulk.debtors[0],id:'demo-only',isDemo:true});bulk.audit=Array.from({length:420},(_,i)=>({id:'audit-'+i,ts:new Date(Date.UTC(2026,9,1,0,i)).toISOString(),userId:i%2?'worker-a':'former-worker',userName:i%2?'พนักงาน ก':'พนักงานเดิม',action:'แก้ไขข้อมูล',detail:'รายการ '+i}));w.localStorage.setItem('freshywater_demo_v8',JSON.stringify(bulk));d.window.close();
 const d2=dom(bulk),w2=d2.window;w2.document.querySelector('#loginCode').value='7716';w2.document.querySelector('#loginBtn').click();w2.document.querySelector('[data-page="debtorsOther"]').click();assert.equal(w2.document.querySelectorAll('.debtor-card').length,30);assert(w2.document.querySelector('.pager').textContent.includes('1000'));w2.document.querySelector('#debtNext').click();assert.equal(w2.document.querySelectorAll('.debtor-card').length,30);assert(w2.document.querySelector('.pager').textContent.includes('2 / 34'));
 w2.document.querySelector('#printReportBtn').click();assert(w2.document.querySelector('#po_qr').checked);w2.document.querySelector('#po_qr').checked=false;w2.document.querySelector('#doPrint').click();await pause();const printed=w2.document.querySelector('#printArea');assert.equal(printed.querySelectorAll('.debtor-report-table').length,1000);assert.equal(printed.querySelectorAll('tbody tr').length,2001);assert(printed.textContent.includes('ราย 999'));const customerTables=[...printed.querySelectorAll('.debtor-report-table')];assert(customerTables[0].querySelector('caption').textContent.includes('ราย 0'));assert(!customerTables[0].textContent.includes('ราย 1'));assert(customerTables.every(t=>t.querySelector('caption')&&t.querySelector('.doc-customer-total')));assert(printed.querySelector('.report-total').textContent.includes('20,020'));assert(printed.querySelector('.report-total').textContent.includes('1001'));assert(/^FWD-[A-Z0-9]{13}$/.test(printed.querySelector('.doc-control strong').textContent.replace('เลขที่ ','')));
 w2.document.querySelector('[data-page="audit"]').click();const history=w2.document.querySelector('#auditEmployeeFilter');assert(history);assert(history.textContent.includes('พนักงานเดิม'));assert(w2.document.querySelector('.audit-filters').textContent.includes('420'));for(let i=0;i<8;i++)w2.document.querySelector('#auditNext').click();assert(w2.document.querySelector('.audit-table').textContent.includes('รายการ 0'),'The history must include records older than the latest 200');const currentHistory=w2.document.querySelector('#auditEmployeeFilter');currentHistory.value='worker-a';currentHistory.dispatchEvent(new w2.Event('change'));assert(w2.document.querySelector('.pager').textContent.includes('1 / 5'));assert(w2.document.querySelector('.audit-filters').textContent.includes('210'));assert(!w2.document.querySelector('.audit-table tbody').textContent.includes('พนักงานเดิม'));
 w2.document.querySelector('[data-page="settings"]').click();w2.document.querySelector('[data-t="system"]').click();w2.document.querySelector('#resetBtn').click();await pause();const preserved=JSON.parse(w2.localStorage.getItem('freshywater_demo_v8'));assert.equal(preserved.debtors.length,1000);assert(preserved.debtors.every(x=>!x.isDemo));d2.window.close();console.log('Passed: Bangkok backups, CSV safety, village codes, debtor continuation keyboard, staff controls, formal print options, immediate theme, profile picker, settings preservation, and 1,000 debtor pagination.');
})().catch(e=>{console.error(e);process.exitCode=1;});

