'use strict';const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{PGlite}=require('@electric-sql/pglite'),S=require('./sync');
const source=fs.readFileSync('app.js','utf8'),runtime=source.slice(source.indexOf('function journalPrefix('),source.indexOf('function supabasePush('));
class Storage{constructor(){this.map=new Map()}get length(){return this.map.size}key(i){return [...this.map.keys()][i]}getItem(k){return this.map.get(k)||null}setItem(k,v){this.map.set(k,String(v))}removeItem(k){this.map.delete(k)}}
const defaults=()=>({business:{name:'Freshy'},header:{},email:{alerts:{}},docPrefix:{},backup:{},doccounters:{},db:{mode:'supabase',supabaseUrl:'https://fixture.supabase.co',supabaseKey:'fixture'}});
(async()=>{const pg=new PGlite(),adminUid='00000000-0000-0000-0000-000000000001';await pg.exec("create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;insert into auth.users values('"+adminUid+"','phatthanapon26@gmail.com',now());");await pg.exec(fs.readFileSync('database.sql','utf8'));const admin=(await pg.query("select set_config('test.uid',$1,false)",[adminUid]),(await pg.query('select freshy_read() as payload')).rows[0].payload.actor),workers=[];
 for(let i=1;i<=10;i++){const authId='00000000-0000-0000-0000-'+String(i+1).padStart(12,'0');await pg.query('insert into auth.users values($1,$2,now())',[authId,'worker'+i+'@test.local']);workers.push({id:'worker-'+i,code:String(1000+i),email:'worker'+i+'@test.local',name:'Worker '+i,role:'staff',status:'active',permissions:{pages:{dashboard:true,customersOther:i!==10,debtorsOther:true,paymentsOther:true,cashsales:true}},authId});}
 await pg.query("update freshy_store set value=$1::jsonb where key='employees'",[JSON.stringify([admin,...workers.map(({authId,...w})=>w)])]);
 let lost=new Set(),failBefore=new Set(['worker-3','worker-6']),requests=0;const contexts=[];
 function context(person,storage=new Storage(),label=person.id){let sequence=0;const logs=[];const c={FreshySync:S,SUPA_COLS:S.collections,defaultSettings:defaults,DB:{settings:defaults()},authIdentity:{id:person.authId},remoteBase:null,remoteSettings:null,session:null,syncTabId:label,syncPromise:null,syncReadPromise:null,syncBusy:false,syncBlocked:false,syncRetryCount:0,syncRetryTimer:null,syncIssues:[],syncViewDirty:false,lastSyncAt:0,currentPage:'dashboard',window:{FRESHY_PREVIEW:false},localStorage:storage,document:{querySelector:()=>null,activeElement:{tagName:'BODY'}},$:()=>null,uid:()=>label+'-generated-'+(++sequence),modalIsOpen:()=>false,renderPage:()=>{},refreshUserChip:()=>{},setStatus:()=>{},toast:(...args)=>logs.push(args),broadcastOnlineChange:()=>{},clearTimeout:()=>{},setTimeout:()=>0,console,Date,me:()=>c.DB.employees?.find(e=>e.id===c.session?.empId),supaCfg:()=>({url:'https://fixture.supabase.co',key:'fixture'}),authFor:()=>({rpc:async(name,body)=>{
  requests++;if(name==='freshy_apply'&&failBefore.delete(person.id))return {error:{message:'fixture network offline'}};
  try{const payload=await pg.transaction(async tx=>{await tx.query("select set_config('test.uid',$1,true)",[person.authId]);await tx.query("select set_config('request.headers',$1,true)",[JSON.stringify({'x-freshy-revision':c.remoteBase?.settings?._resetRevision||''})]);return (await tx.query('select '+name+'('+ (name==='freshy_apply'?'$1::jsonb':'') +') as payload',name==='freshy_apply'?[JSON.stringify(body.changes)]:[])).rows[0].payload;});
   if(name==='freshy_apply'&&!lost.has(person.id)){lost.add(person.id);return {error:{message:'TimeoutError: response lost after commit'}};}return {data:payload};
  }catch(error){return {error:{message:error.message,code:error.code}};}
 }})};vm.createContext(c);vm.runInContext(runtime,c);return {c,logs};}
 for(const worker of workers){const {c}=context(worker);c.installRemote((await c.authFor().rpc('freshy_read')).data,[]);for(let i=0;i<20;i++){const customer={id:worker.id+'-customer-'+i,name:'Customer '+i,area:'other',createdBy:worker.id,createdAt:new Date().toISOString()};c.DB.customers.push(customer);c.DB.debtors.push({id:worker.id+'-debt-'+i,customerId:customer.id,customerName:customer.name,area:'other',createdBy:worker.id,createdAt:new Date().toISOString(),debtDate:'2026-10-07',status:'unpaid',jugs:1,packs:0,jugAmount:15,packAmount:0,total:15});}c.DB.audit.push({id:worker.id+'-explicit-audit',userId:worker.id,userName:worker.name,ts:new Date().toISOString(),action:'เพิ่มลูกหนี้',detail:'20 รายการ'});c.safeCache();contexts.push(c);}
 contexts[0].DB.debtors.push({id:'bad-amount',customerName:'Incorrect fixture',area:'other',createdBy:'worker-1',status:'unpaid',jugs:1,packs:0,jugAmount:-15,packAmount:0,total:-15});
 for(let i=0;i<5;i++)await Promise.all(contexts.map(c=>c.flushOnline()));
 const verify=async()=>pg.transaction(async tx=>{await tx.query("select set_config('test.uid',$1,true)",[adminUid]);return (await tx.query('select freshy_read() as payload')).rows[0].payload;});let payload=await verify();assert.equal(payload.data.customers.length,200);assert.equal(payload.data.debtors.length,200);assert.equal(payload.data.debtors.reduce((sum,d)=>sum+d.total,0),3000);assert.equal(new Set(payload.data.debtors.map(d=>d.id)).size,200);assert.equal(contexts[0].syncIssues.length,1);assert.equal(contexts[0].syncIssues[0].change.id,'bad-amount');assert(contexts.every(c=>S.diff(c.remoteBase,S.shared(c.DB)).length===0));
 assert.equal(payload.data.audit.filter(x=>x.id.endsWith('-explicit-audit')).length,10);
 // The hidden staff audit response can be lost after commit; an identical retry is acknowledged once.
 const auditClient=contexts[1],auditChange={collection:'audit',id:'audit-lost-reply',expected:null,value:{id:'audit-lost-reply',userId:workers[1].id,userName:workers[1].name,ts:new Date().toISOString(),action:'เพิ่มลูกค้า',detail:'Network retry fixture'}};lost.delete(workers[1].id);auditClient.DB.audit.push(auditChange.value);await auditClient.flushOnline();assert(await auditClient.flushOnline());assert.equal(auditClient.syncIssues.length,0);assert.equal((await verify()).data.audit.filter(x=>x.id==='audit-lost-reply').length,1);
 const codes=await Promise.all(contexts.map(c=>c.rpc('freshy_customer_code')));assert.equal(new Set(codes).size,10);assert.deepEqual(codes.slice().sort(),Array.from({length:10},(_,i)=>'C'+String(i+1).padStart(3,'0')));
 // The database rejects a reused customer code without overwriting the existing row.
 const codeOwner=contexts[2];codeOwner.DB.customers.push({id:'unique-code',code:codes[0],name:'Unique code',area:'other',createdBy:workers[2].id});await codeOwner.flushOnline();const other=contexts[3];other.DB.customers.push({id:'duplicate-code',code:codes[0],name:'Duplicate',area:'other',createdBy:workers[3].id});await other.flushOnline();assert(other.syncIssues.some(x=>/DUPLICATE_CUSTOMER_CODE/.test(x.reason)));assert(!(await verify()).data.customers.some(x=>x.id==='duplicate-code'));
 for(const c of contexts){await c.supabaseFetch();assert.equal(c.DB.debtors.length,200,'All staff see the full shared debtor collection');}
 const {c:adminA}=context({...admin,authId:adminUid},new Storage(),'admin-a'),sharedStorage=new Storage(),{c:adminB}=context({...admin,authId:adminUid},sharedStorage,'admin-b');adminA.installRemote(payload,[]);adminB.installRemote(payload,[]);
 const id=payload.data.customers[0].id;adminA.DB.customers.find(x=>x.id===id).address='Changed address';adminB.DB.customers.find(x=>x.id===id).name='Changed name';await Promise.all([adminA.flushOnline(),adminB.flushOnline()]);await Promise.all([adminA.flushOnline(),adminB.flushOnline()]);payload=await verify();const changed=payload.data.customers.find(x=>x.id===id);assert.equal(changed.address,'Changed address');assert.equal(changed.name,'Changed name');assert.equal(adminB.syncIssues.length,0);
 // A true same-field conflict is retained for review and cannot block another row.
 await Promise.all([adminA.supabaseFetch(),adminB.supabaseFetch()]);adminA.DB.customers.find(x=>x.id===id).name='Choice A';adminB.DB.customers.find(x=>x.id===id).name='Choice B';adminB.DB.customers.push({id:'independent-after-conflict',name:'Independent',createdBy:admin.id,area:'other'});await adminA.flushOnline();await adminB.flushOnline();assert.equal(adminB.syncIssues.length,1);assert.equal((await verify()).data.customers.find(x=>x.id===id).name,'Choice A');assert((await verify()).data.customers.some(x=>x.id==='independent-after-conflict'));assert.equal(S.diff(adminB.remoteBase,S.shared(adminB.DB)).length,0);
 // Separate journals preserve unsent records from two tabs sharing localStorage.
 const {c:tab1}=context({...admin,authId:adminUid},sharedStorage,'tab-one'),{c:tab2}=context({...admin,authId:adminUid},sharedStorage,'tab-two');payload=await verify();tab1.installRemote(payload,[]);tab2.installRemote(payload,[]);tab1.DB.customers.push({id:'offline-tab-one',name:'Tab one',createdBy:admin.id,area:'other'});tab2.DB.customers.push({id:'offline-tab-two',name:'Tab two',createdBy:admin.id,area:'other'});tab1.safeCache();tab2.safeCache();const restored=tab2.loadDraft();assert(restored.data.customers.some(x=>x.id==='offline-tab-one'));assert(restored.data.customers.some(x=>x.id==='offline-tab-two'));
 // Read while a form remains open preserves the form and still receives committed rows.
 tab1.modalIsOpen=()=>true;await tab1.supabaseFetch();assert(tab1.DB.customers.some(x=>x.id==='independent-after-conflict'));
 // A reset may not resurrect old drafts: keep an exportable archive instead.
 const oldChanges=S.diff(tab2.remoteBase,S.shared(tab2.DB));tab2.acceptRemote({actor:admin,data:{...payload.data,settings:{...payload.data.settings,_resetRevision:'explicit-reset'},customers:[]}},oldChanges);assert.equal(tab2.DB.customers.length,0);assert(tab2.syncIssues.some(x=>x.change.id==='offline-tab-two'&&/ก่อนแอดมินล้าง/.test(x.reason)));assert.equal(S.diff(tab2.remoteBase,S.shared(tab2.DB)).length,0);
 await pg.close();console.log('Passed: 10 employee clients on PostgreSQL, 200 customers + 200 debts, 3,000 baht exact, lost replies and pre-write offline failures, zero duplicates, hidden audit lost-reply recovery, factory-wide customer codes, invalid row isolation, cross-device reads, disjoint concurrent edits, real conflicts preserved, separate tab recovery, open-form refresh, and reset archive without resurrection. Requests: '+requests);
})().catch(error=>{console.error(error);process.exitCode=1;});
