const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const S=require('./sync.js');
const blank=()=>Object.fromEntries(S.collections.map(k=>[k,k==='settings'?{business:{name:'Freshy'},doccounters:{}}:[]]));
const base=blank();base.settings.db={mode:'supabase'};
const current=S.shared(base);
assert.equal(S.diff(S.shared(base),current).length,0);
const queued=Array.from({length:10},(_,i)=>({collection:'customers',id:'test-'+i,expected:null,value:{id:'test-'+i,name:'Test '+i}}));
const server=blank();server.customers=[{id:'other-device',name:'Existing'}];
const recovered=S.overlay(server,S.rebase(server,queued));
assert.equal(recovered.customers.length,11);
assert.equal(S.rebase(recovered,queued).length,0,'A committed response lost to timeout must not duplicate writes');
assert.throws(()=>S.rebase({customers:[{id:'test-0',name:'Other change'}]},[queued[0]]),/CONFLICT:customers/);
const settings={collection:'settings',id:'settings',expected:{business:{name:'Old',phone:'1'},doccounters:{FWD:1},db:{mode:'supabase'}},value:{business:{name:'New',phone:'1'},doccounters:{FWD:2}}};
const rebased=S.rebase({settings:{business:{name:'Old',phone:'2'},doccounters:{FWD:3}}},[settings])[0];
assert.deepEqual(rebased.value,{business:{name:'New',phone:'2'},doccounters:{FWD:3}});
assert.throws(()=>S.rebase({settings:{business:{name:'Different',phone:'1'},doccounters:{FWD:1}}},[settings]),/CONFLICT:settings/);
const app=fs.readFileSync(__dirname+'/app.js','utf8');
const install=app.slice(app.indexOf('function installRemote('),app.indexOf('async function rpc('));
const raw={business:{name:'Live'},doccounters:{},db:{old:true}};
const context={FreshySync:S,SUPA_COLS:S.collections,DB:{settings:{db:{mode:'supabase'}}},defaultSettings:()=>({business:{name:'Default'},email:{enabled:false},db:{mode:'demo'}}),safeCache:()=>{},remoteBase:null,remoteSettings:null};
vm.createContext(context);vm.runInContext(install,context);
context.installRemote({actor:{id:'admin'},data:{settings:raw,employees:[{id:'admin'}]}},[]);
assert.equal(S.diff(context.remoteBase,S.shared(context.DB)).length,0,'UI defaults must not create phantom pending settings');
assert.equal(context.remoteSettings.business.name,'Live');
assert.equal(context.remoteSettings.db.old,true,'Expected settings must match the exact server JSON, including legacy keys');
assert.equal(context.remoteBase.settings.db,undefined,'Device connection settings must stay out of the shared baseline');
assert.match(fs.readFileSync(__dirname+'/database.sql','utf8'),/errcode='PT409'/);
assert.doesNotMatch(fs.readFileSync(__dirname+'/database.sql','utf8'),/errcode='40001'/);
console.log('Passed: 10 queued writes, replay after timeout, cross-device conflicts, settings merge, raw settings baseline, PT409.');
