'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{JSDOM}=require('jsdom'),{PGlite}=require('@electric-sql/pglite');
const source=fs.readFileSync('app.js','utf8');
(async()=>{
 const d=new JSDOM('<main><input id="debtorSearch" value="ลูกค้า"><p id="count">1</p></main>',{url:'https://fixture.test/',runScripts:'outside-only'}),w=d.window;let renders=0,open=false;
 Object.assign(w,{session:{empId:'admin'},syncViewDirty:true,currentPage:'debtorsNai',$:s=>w.document.querySelector(s),modalIsOpen:()=>open,refreshUserChip:()=>{},renderPage:()=>{renders++;w.document.querySelector('main').innerHTML='<input id="debtorSearch"><p id="count">2</p>';}});
 w.eval(source.slice(source.indexOf('function refreshSyncedView('),source.indexOf('function quarantineSyncChange(')));
 let input=w.document.querySelector('#debtorSearch');input.focus();input.setSelectionRange(1,3);w.refreshSyncedView();input=w.document.querySelector('#debtorSearch');assert.equal(renders,1);assert.equal(w.document.querySelector('#count').textContent,'2');assert.equal(input.value,'ลูกค้า');assert.equal(w.document.activeElement,input);assert.equal(input.selectionStart,1);assert.equal(input.selectionEnd,3);assert.equal(w.syncViewDirty,false);
 open=true;w.syncViewDirty=true;w.refreshSyncedView();assert.equal(renders,1);assert.equal(w.syncViewDirty,true);open=false;w.currentPage='settings';w.refreshSyncedView();assert.equal(renders,1);d.window.close();
 const pg=new PGlite(),adminUid='00000000-0000-0000-0000-000000000001',staffUid='00000000-0000-0000-0000-000000000002';await pg.exec("create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;insert into auth.users values('"+adminUid+"','phatthanapon26@gmail.com',now()),('"+staffUid+"','staff@test.local',now());");await pg.exec(fs.readFileSync('database.sql','utf8'));await pg.query("select set_config('test.uid',$1,false)",[adminUid]);const admin=(await pg.query('select freshy_read() as payload')).rows[0].payload.actor;
 const staff={id:'staff',code:'001',name:'Staff',email:'staff@test.local',role:'staff',status:'active',permissions:{pages:{debtorsOther:true,paymentsOther:true}}},other={id:'private-staff',role:'staff',name:'Other Staff'};
 const put=async(k,v)=>pg.query('insert into freshy_store(key,value) values($1,$2::jsonb) on conflict(key) do update set value=excluded.value',[k,JSON.stringify(v)]);await put('employees',[admin,staff,other]);await put('customers',[{id:'admin-other',name:'Shared',area:'other',createdBy:admin.id},{id:'admin-nai',name:'Forbidden page',area:'nai',createdBy:admin.id},{id:'own',name:'Own',area:'other',createdBy:staff.id},{id:'other-staff',name:'Private',area:'other',createdBy:other.id}]);const base={customerName:'Fixture',jugs:1,packs:0,jugAmount:15,packAmount:0,total:15,status:'unpaid',createdAt:new Date().toISOString(),debtDate:'2026-10-08'};await put('debtors',[{...base,id:'shared-debt',customerId:'admin-other',area:'other',createdBy:admin.id},{...base,id:'denied-debt',customerId:'admin-nai',area:'nai',createdBy:admin.id},{...base,id:'own-debt',customerId:'own',area:'other',createdBy:staff.id},{...base,id:'private-debt',customerId:'other-staff',area:'other',createdBy:other.id}]);
 const fingerprint=async()=> (await pg.query("select md5(string_agg(key||':'||value::text,'|' order by key)) as hash from freshy_store")).rows[0].hash, before=await fingerprint();await pg.exec(fs.readFileSync('shared-payments-review.sql','utf8'));assert.equal(await fingerprint(),before,'Workflow migration must not alter any business row');
 const read=async()=> (await pg.query('select freshy_read() as payload')).rows[0].payload;assert.equal((await read()).data.debtors.length,4);await pg.query("select set_config('test.uid',$1,false)",[staffUid]);let p=await read();assert.deepEqual(p.data.debtors.map(x=>x.id).sort(),['denied-debt','own-debt','private-debt','shared-debt']);assert.deepEqual(p.data.customers.map(x=>x.id).sort(),['admin-nai','admin-other','other-staff','own']);assert.deepEqual(p.data.employees,[staff]);assert(p.recorders.some(x=>x.id===admin.id&&x.name));assert(p.recorders.every(x=>Object.keys(x).sort().join(',')==='id,name'));
 const shared=p.data.debtors.find(x=>x.id==='shared-debt');await assert.rejects(()=>pg.query('select freshy_apply($1::jsonb)',[JSON.stringify([{collection:'debtors',id:shared.id,expected:shared,value:{...shared,status:'paid'}}])]),/PAYMENT_WORKFLOW_REQUIRED/);assert.equal(await fingerprint(),before);
 assert.equal((await pg.query("select has_function_privilege('anon','freshy_read()','execute') as allowed")).rows[0].allowed,false);
 const c={DB:{employees:[staff]},remoteRecorders:p.recorders,authIdentity:{id:staffUid},me:()=>staff,isAdmin:()=>false};vm.createContext(c);vm.runInContext(source.slice(source.indexOf('function canManageRecord('),source.indexOf('/* ---------- email alerts',source.indexOf('function canManageRecord('))),c);assert.equal(c.scopeRows(p.data.debtors).length,4,'Online view must show all shared operational records');assert(!c.canManageRecord(shared));assert(c.canManageRecord(p.data.debtors.find(x=>x.id==='own-debt')));c.authIdentity=null;assert.equal(c.scopeRows(p.data.debtors).length,4,'Demo must match shared visibility');
 await pg.close();console.log('Passed: refresh preserves typing/caret; open forms and settings remain intact; all actors see every operational record; personnel details remain private; migration preserves every stored row; generic writes cannot bypass payment review; anonymous reads remain denied.');
})().catch(e=>{console.error(e);process.exitCode=1;});
